# Site settings
author: Ben Hayes
title: 
header-img: img/home-bg.png
email: b.t.hayes@comcast.net
copyright_name: Ben Hayes
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ben-the-boy

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
